version: '3.1'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    restart: on-failure
  kafka:
    image: wurstmeister/kafka
    container_name: kashka
    restart: on-failure
    depends_on:
      - zookeeper
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_MESSAGE_MAX_BYTES: 20970000
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_DELETE_TOPIC_ENABLE: 'true'
    ports:
      - '9092:9092'

  database:
    image: postgres:12
    container_name: databashe
    restart: on-failure
    environment:
      POSTGRES_USER: mr_anderson
      POSTGRES_PASSWORD: the_chosen_one
    ports:
      - 5432:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data

  redis:
    image: redis:6.2.6
    container_name: redish
    restart: on-failure
    volumes:
      - ./redis_data:/bitnami/redis
    ports:
      - '6379:6379'

